// <auto-generated />
using System;
using DocumentAutomation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DocumentAutomation.Migrations
{
    [DbContext(typeof(DocumentDbContext))]
    partial class DocumentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DocumentAutomation.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#FF5733",
                            CreatedDate = new DateTime(2026, 3, 5, 14, 36, 0, 95, DateTimeKind.Local).AddTicks(2749),
                            Description = "Шаблоны договоров",
                            Name = "Договоры"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#33FF57",
                            CreatedDate = new DateTime(2026, 3, 5, 14, 36, 0, 95, DateTimeKind.Local).AddTicks(2930),
                            Description = "Шаблоны счетов",
                            Name = "Счета"
                        },
                        new
                        {
                            Id = 3,
                            Color = "#3357FF",
                            CreatedDate = new DateTime(2026, 3, 5, 14, 36, 0, 95, DateTimeKind.Local).AddTicks(2933),
                            Description = "Шаблоны писем",
                            Name = "Письма"
                        },
                        new
                        {
                            Id = 4,
                            Color = "#F033FF",
                            CreatedDate = new DateTime(2026, 3, 5, 14, 36, 0, 95, DateTimeKind.Local).AddTicks(2935),
                            Description = "Шаблоны актов",
                            Name = "Акты"
                        });
                });

            modelBuilder.Entity("DocumentAutomation.Models.DocumentTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Templates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Content = "Договор аренды №{{CONTRACT_NUMBER}} от {{DATE}}\n\nКомпания {{COMPANY_NAME}} в лице...",
                            CreatedByUserId = 1,
                            CreatedDate = new DateTime(2026, 3, 5, 14, 36, 0, 100, DateTimeKind.Local).AddTicks(3529),
                            Description = "Шаблон договора аренды помещения",
                            Name = "Договор аренды"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Content = "Счет №{{INVOICE_NUMBER}} от {{DATE}}\n\nПлательщик: {{CLIENT_NAME}}\nСумма: {{PRICE}} руб.",
                            CreatedByUserId = 1,
                            CreatedDate = new DateTime(2026, 3, 5, 14, 36, 0, 100, DateTimeKind.Local).AddTicks(3637),
                            Description = "Шаблон счета на оплату услуг",
                            Name = "Счет на оплату"
                        });
                });

            modelBuilder.Entity("DocumentAutomation.Models.GeneratedDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("GeneratedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("GeneratedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedByUserId");

                    b.HasIndex("TemplateId");

                    b.HasIndex("UserId");

                    b.ToTable("GeneratedDocuments");
                });

            modelBuilder.Entity("DocumentAutomation.Models.TemplateVariable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("string");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("TemplateVariables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 3, 5, 14, 36, 0, 95, DateTimeKind.Local).AddTicks(3834),
                            DataType = "string",
                            DefaultValue = "ООО Ромашка",
                            Description = "Название компании",
                            Name = "COMPANY_NAME"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 3, 5, 14, 36, 0, 95, DateTimeKind.Local).AddTicks(3951),
                            DataType = "string",
                            DefaultValue = "",
                            Description = "Имя клиента",
                            Name = "CLIENT_NAME"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 3, 5, 14, 36, 0, 100, DateTimeKind.Local).AddTicks(1393),
                            DataType = "date",
                            DefaultValue = "05.03.2026",
                            Description = "Дата",
                            Name = "DATE"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2026, 3, 5, 14, 36, 0, 100, DateTimeKind.Local).AddTicks(1405),
                            DataType = "decimal",
                            DefaultValue = "0",
                            Description = "Сумма",
                            Name = "PRICE"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2026, 3, 5, 14, 36, 0, 100, DateTimeKind.Local).AddTicks(1407),
                            DataType = "string",
                            DefaultValue = "001",
                            Description = "Номер договора",
                            Name = "CONTRACT_NUMBER"
                        });
                });

            modelBuilder.Entity("DocumentAutomation.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 3, 5, 14, 36, 0, 66, DateTimeKind.Local).AddTicks(595),
                            Email = "admin@example.com",
                            FullName = "Администратор",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("DocumentAutomation.Models.DocumentTemplate", b =>
                {
                    b.HasOne("DocumentAutomation.Models.Category", "Category")
                        .WithMany("Templates")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DocumentAutomation.Models.User", "CreatedBy")
                        .WithMany("Templates")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("DocumentAutomation.Models.GeneratedDocument", b =>
                {
                    b.HasOne("DocumentAutomation.Models.User", "GeneratedBy")
                        .WithMany()
                        .HasForeignKey("GeneratedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DocumentAutomation.Models.DocumentTemplate", "Template")
                        .WithMany("GeneratedDocuments")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DocumentAutomation.Models.User", null)
                        .WithMany("GeneratedDocuments")
                        .HasForeignKey("UserId");

                    b.Navigation("GeneratedBy");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("DocumentAutomation.Models.TemplateVariable", b =>
                {
                    b.HasOne("DocumentAutomation.Models.DocumentTemplate", "Template")
                        .WithMany("Variables")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Template");
                });

            modelBuilder.Entity("DocumentAutomation.Models.Category", b =>
                {
                    b.Navigation("Templates");
                });

            modelBuilder.Entity("DocumentAutomation.Models.DocumentTemplate", b =>
                {
                    b.Navigation("GeneratedDocuments");

                    b.Navigation("Variables");
                });

            modelBuilder.Entity("DocumentAutomation.Models.User", b =>
                {
                    b.Navigation("GeneratedDocuments");

                    b.Navigation("Templates");
                });
#pragma warning restore 612, 618
        }
    }
}
